import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-black py-12 text-center text-white text-2xl font-bold">
          <Link href={'/'} className="w-fit">Gate Information sharing</Link>
        </div>
        <div className="dark:bg-neutral-800 min-h-screen">
        {children}
        </div>
        <div className="bg-black py-16"></div>
      </body>
    </html>
  );
}
